<?xml version="1.0" ?>
<testsuite name="TestSum-20230204144109" tests="5" time="0.688" failures="0" errors="4">
	<testcase classname="TestSum" name="test_pass" time="0.672"/>
	<testcase classname="TestSum" name="test_empty" time="0.015">
		<error type="FileNotFoundError" message="[Errno 2] No such file or directory: ''"><![CDATA[Traceback (most recent call last):
  File "c:\Users\wmpsa\Desktop\Capstone\Capstone\transcriberTest.py", line 15, in test_empty
    output = transcriber.transcribe(data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\wmpsa\Desktop\Capstone\Capstone\transcriber.py", line 67, in transcribe
    fs, data = wavfile.read(AUDIO_FILE) # load the data
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wmpsa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\scipy\io\wavfile.py", line 647, in read
    fid = open(filename, 'rb')
          ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''
]]></error>
	</testcase>
	<testcase classname="TestSum" name="test_fileNotFound" time="0.001">
		<error type="FileNotFoundError" message="[Errno 2] No such file or directory: 'something.wav'"><![CDATA[Traceback (most recent call last):
  File "c:\Users\wmpsa\Desktop\Capstone\Capstone\transcriberTest.py", line 30, in test_fileNotFound
    output = transcriber.transcribe(data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\wmpsa\Desktop\Capstone\Capstone\transcriber.py", line 67, in transcribe
    fs, data = wavfile.read(AUDIO_FILE) # load the data
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wmpsa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\scipy\io\wavfile.py", line 647, in read
    fid = open(filename, 'rb')
          ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'something.wav'
]]></error>
	</testcase>
	<testcase classname="TestSum" name="test_isNotString" time="0.000">
		<error type="OSError" message="[WinError 6] The handle is invalid"><![CDATA[Traceback (most recent call last):
  File "c:\Users\wmpsa\Desktop\Capstone\Capstone\transcriberTest.py", line 20, in test_isNotString
    output = transcriber.transcribe(data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\wmpsa\Desktop\Capstone\Capstone\transcriber.py", line 67, in transcribe
    fs, data = wavfile.read(AUDIO_FILE) # load the data
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wmpsa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\scipy\io\wavfile.py", line 647, in read
    fid = open(filename, 'rb')
          ^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid
]]></error>
	</testcase>
	<testcase classname="TestSum" name="test_notWav" time="0.000">
		<error type="FileNotFoundError" message="[Errno 2] No such file or directory: 'test.mp3'"><![CDATA[Traceback (most recent call last):
  File "c:\Users\wmpsa\Desktop\Capstone\Capstone\transcriberTest.py", line 25, in test_notWav
    output = output = transcriber.transcribe(data)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\wmpsa\Desktop\Capstone\Capstone\transcriber.py", line 67, in transcribe
    fs, data = wavfile.read(AUDIO_FILE) # load the data
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wmpsa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\scipy\io\wavfile.py", line 647, in read
    fid = open(filename, 'rb')
          ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'test.mp3'
]]></error>
	</testcase>
	<system-out><![CDATA[]]></system-out>
	<system-err><![CDATA[]]></system-err>
</testsuite>
